namespace Kentico.Kontent.Recommendations.Models
{
    internal class CreateVisitorRequest
    {
        /// <summary>
        /// Visit(or) id - generated by the customer or by the SDK, tracked across the application
        /// </summary>
        /// <example>visitorId123</example>
        public string VisitId { get; set; }

        /// <summary>
        /// Extra details about the visitor
        /// </summary>
        public VisitorDetails Visitor { get; set; }
    }
}
