namespace Kentico.Kontent.Recommendations.Models
{
    /// <summary>
    /// Request for Kontent Search
    /// </summary>
    public class SearchRequest

    {
        /// <summary>
        /// REQUIRED: Visit(or) id - generated by the customer/3rd party (or by the SDK Helper), should be tracked across the application
        /// </summary>
        public string VisitId { get; set; }

        /// <summary>
        /// REQUIRED: Codename of currently viewed content item
        /// </summary>
        public string Query { get; set; }

        /// <summary>
        /// REQUIRED: Number of recommendations that will be returned
        /// Rarely, smaller number of recommendations can be returned, therefore, there should be a user fallback implemented in case of this occurence
        /// </summary>
        public int ResultCount { get; set; }

        /// <summary>
        /// OPTIONAL: Content type of recommended content items
        /// If no type is specified, any content type can be returned
        /// </summary>
        public string RequestedTypeCodename { get; set; }

    }
}
